### DISCUSSION TITLE
Gateway File! TLS config

### DISCUSSION THREAD

**Discussion by aarongodin** [narrowlink/narrowlink#121] [Q&A]
Hi folks, is there documentation for the `File!` TLS config? I see it mentioned in [these docs](https://narrowlink.com/docs/gateway#configuration) but can't find what the structure looks like. Moreover, it would be helpful if there was a central place where all YAML was documented, or a JSON schema that shows the allowed YAML structure/API.

**Comment by aarongodin** [comment]
Of course, right after I made this post, I see that it's just commented out in the section I linked:

```yaml
  # tls_config: !File /etc/cert/domain.example/fullchain+privkey.pem
```

Still I think my previous question has merit - anywhere I can find a JSON schema or something that outlines the structure of every YAML document?

**Comment by aarongodin** [comment]
Now tracing back to the original question, I'm getting an error with the config when using the following for the gateway:

```
name: <redacted>
secret: [<redacted>]
services:
- !Wss
  domains: ["<redacted>"]
  listen_addr: "0.0.0.0:443"
  tls_config: !Acme
    email: "<redacted>"
    challenge_type: Http01
    directory_url: https://acme-v02.api.letsencrypt.org/directory
- !Wss
  domains: ["<redacted>"]
  listen_addr: "0.0.0.0:443"
  tls_config: !File /etc/certs/<redacted>/fullchain.pem
- !Ws
  domains: ["<redacted>", "<redacted>"]
  listen_addr: "0.0.0.0:80"
```

I assumed I could have multiple secure web socket services to have different TLS configs. The gateway doesn't explain why the config is invalid - anyone able to explain what I did wrong?

**Reply by aarongodin** [reply]
I'm thinking that what I've done incorrectly is that you cannot have two services listening on the same host:port. Based on that assumption, I'm not sure what I can do to have different `tls_config` blocks for two different domains.

**Comment by SajjadPourali** [comment]
Hello,
The documentation is intended to explain all the stable options. However, I agree that it could be made more readable. Regarding the schema, I didn't find the JSON schema particularly useful for this purpose. Do you have any other suggestions to improve the documentation in this part?

> I'm thinking that what I've done incorrectly is that you cannot have two services listening on the same host:port. Based on that assumption, I'm not sure what I can do to have different `tls_config` blocks for two different domains.

That's correct; you cannot run two services on the same address and port. From what I see, there are two WebSocket Secure (WSS) services using the same address.


Please let me know if this helps, and don’t hesitate to ask any further questions.

**Reply by aarongodin** [reply]
Sure, makes sense thanks for confirming! I don't have great ideas other than having a section of documentation that defines the entire object structure with a description of each config option. [Here's an example](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#server) of the grafana config file documented item by item. Or, API docs like Stripe are good at outlining the structure of an object and [further documenting each field](https://docs.stripe.com/api/balance/balance_object).

If I understand correctly, I need the same TLS config to apply to all secure services hosted by the gateway. I think this will work but there's an aspect to migration that makes this difficult. A domain I'm hosting on a different service is already secured by a letsencrypt cert, so my idea was to move the cert to the gateway and use the file directive. But, I might be able to make the gateway the owner, I just don't know enough about letsencrypt to make this happen.

**Reply by aarongodin** [reply]
I did try and modify the config to only have one service listening on `0.0.0.0:443` and for that service to use the `File!` TLS config. This still causes the `Error: InvalidConfig` to happen.

```yaml
name: <redacted>
secret: [<redacted>]
services:
- !Wss
  domains: ["<redacted>"]
  listen_addr: "0.0.0.0:443"
  tls_config: !File /etc/certs/<redacted>/fullchain.pem
- !Ws
  domains: ["<redacted>"]
  listen_addr: "0.0.0.0:80"
```

**Reply by SajjadPourali** [reply]
> I did try and modify the config to only have one service listening on `0.0.0.0:443` and for that service to use the `File!` TLS config. This still causes the `Error: InvalidConfig` to happen.
> 
> ```yaml
> name: <redacted>
> secret: [<redacted>]
> services:
> - !Wss
>   domains: ["<redacted>"]
>   listen_addr: "0.0.0.0:443"
>   tls_config: !File /etc/certs/<redacted>/fullchain.pem
> - !Ws
>   domains: ["<redacted>"]
>   listen_addr: "0.0.0.0:80"
> ```

Could you please use this format? 

```yaml
name: <redacted>
secret: [<redacted>]
services:
- !Wss
  domains: ["<redacted>"]
  listen_addr: "0.0.0.0:443"
  tls_config: !File
    domains: ["<redacted>"]
    cert_path: /etc/certs/<redacted>/fullchain.pem
```
