### DISCUSSION TITLE
port forward not work - Key Not Found

### DISCUSSION THREAD

**Discussion by wanetcn** [narrowlink/narrowlink#27] [Q&A] [answered]
I configured the key in the agent as follows: tokens: # list of tokens
```yaml
- !Agent # agent token 
  uid: 00000000-0000-0000-0000-000000000001 # agent uid, please use a unique uid for each user 
  name: office # agent name, please use a unique name for each agent 
  exp: 1804067200 # expiration time in seconds since epoch (Monday, January 1, 2024 0:00:00 GMT) 
  key: nothingAtall 
```
I used the following command in the client: 
```bash
./narrowlink-x86_64-apple-darwin forward -k nothingAtall -n office -l 127.0.0.1:4433 192.168.50.7:3389 
```
However, I cannot connect to port 3389 on 50.7 through the local 4433 port. The error log of the client is as follows: 
```
[2023-08-22T01:57:25Z DEBUG narrowlink_network::transport] using rustls to connect to XXXXX:443 
[2023-08-22T01:57:26Z DEBUG narrowlink] Connection Error: Key Not Found [2023-08-22T01:57:26Z DEBUG narrowlink_network::ws] ws connection status: 101 Switching Protocols 
[2023-08-22T01:57:26Z WARN narrowlink] Key Not Found : 192.168.50.7:3389
```
I tried changing the key to `nothingAtall` when generating the token in the agent, but the error remained the same.

**Comment by SajjadPourali** [comment, marked as answer]
You didn't set the encryption key in the agent configuration file, but you are going to connect to the agent with the key that you've set on the client. The agent's key should be set its config file (`agent.yaml`), and there is not `key` parameter in the token.

e.g.,:
```yaml
gateway: x.x.x.x:443
token: eyJ0e....pN1c
key: nothingAtall
```
I think you might have misunderstood the [end-to-end encryption](https://narrowlink.com/docs/extended-tutorial/end-to-end-encryption) aspect. I suggest taking another look at it.

You can also simply omit using `-k` to ignore use of E2EE.

I would also appreciate it if you could use more precise titles for the discussions and placing the codes/logs into a code section to make it organized.
