### DISCUSSION TITLE
How to test the QUIC http3 UDP transport?

### DISCUSSION THREAD

**Discussion by 9to1url** [narrowlink/narrowlink#56] [Q&A] [answered]
I found the doc on website still using ws wss, anything I need to change it in Gateway? thanks

**Comment by SajjadPourali** [comment]
The gateway still uses WS/WSS; the QUIC connections are used only for peer-to-peer (P2P) connections at this time. Therefore, you need to have the same configuration.

**Reply by 9to1url** [reply]
Is that possible to enable Gateway also using QUIC/HTTP3 ? thanks

**Reply by 9to1url** [reply]
Another question: for WS/WSS can it tunnel UDP traffic? thanks

**Reply by SajjadPourali** [reply]
> Is that possible to enable Gateway also using QUIC/HTTP3 ? thanks

It is part of the future plans


> Another question: for WS/WSS can it tunnel UDP traffic? thanks

Yes, it can. just use `-u` arg to create a udp tunnel on top of the WS/WSS

**Reply by 9to1url** [reply]
I check all the --help can't find the -u option, could you give the command line examples?

**Reply by SajjadPourali** [reply, marked as answer]
When using the proxy mode, it automatically detects and transfers UDP packets using the SOCKS5 protocol. For the connect or forward modes, you can use the `-u` option.

```bash
narrowlink f -h
narrowlink c -h
```

https://github.com/narrowlink/narrowlink/blob/main/client/forward.help.arg#L18

```bash
narrowlink f -un <agent name> <remote_addr:remote_port>
```
https://github.com/narrowlink/narrowlink/blob/main/client/connect.help.arg#L17
```bash
narrowlink c -un <agent name> <remote_addr:remote_port>
```
Options:
    `-u`: UDP mode
    `-n`: Agent name
    `-un`: UDP mode + Agent name

-----


If you are looking for a method to capture system-wide network traffic without using a proxy, I am currently working on it: https://github.com/narrowlink/narrowlink/issues/55

**Reply by 9to1url** [reply]
great, but I have trouble to generate the token-generator.yaml

I edit the sample one in token-generator code, but still get this:
❯ narrowlink-token-generator token-generator.yaml
Error: InvalidConfig

```
secret: [118,101,72,65,78,82,69,78] # The secret for signing tokens, It must be the same as the gateway token secret, it is as byte array
tokens: # list of tokens
  - !Client # client token
    uid: 1a3248b2-d78e-415b-abbc-4aa781afae65 # client uid, please use a unique uid for each user
    name: client01 # client name, please use a unique name for each client
    exp: 1710227806 # expiration time in seconds since epoch
    policies: [1] # list of policy ids, it must be the same as the policy id in the client policy token, all the policies must be satisfied

  - !ClientPolicy # client policy token
    uid: 1a3248b2-d78e-415b-abbc-4aa781afae65
    name: client01 # client name, please use a unique name for each client
    exp: 1710227806 # expiration time in seconds since epoch
    pid: 1 # policy id, it must be the same as the policy id in the client token
    policy: # policies for this client
      type: !BlackList # !WhiteList or !BlackList
      policies: # list of policies
        - !Ip # policy based on the destination ip address
          - !Any # !Any means any agent, !Agent agent_name means the agent with the name agent_name
          - UDP # protocol
```

**Comment by SajjadPourali** [comment]
> great, but I have trouble to generate the token-generator.yaml
> 
> I edit the sample one in token-generator code, but still get this: ❯ narrowlink-token-generator token-generator.yaml Error: InvalidConfig
> 
> ```
> secret: [118,101,72,65,78,82,69,78] # The secret for signing tokens, It must be the same as the gateway token secret, it is as byte array
> tokens: # list of tokens
>   - !Client # client token
>     uid: 1a3248b2-d78e-415b-abbc-4aa781afae65 # client uid, please use a unique uid for each user
>     name: client01 # client name, please use a unique name for each client
>     exp: 1710227806 # expiration time in seconds since epoch
>     policies: [1] # list of policy ids, it must be the same as the policy id in the client policy token, all the policies must be satisfied
> 
>   - !ClientPolicy # client policy token
>     uid: 1a3248b2-d78e-415b-abbc-4aa781afae65
>     name: client01 # client name, please use a unique name for each client
>     exp: 1710227806 # expiration time in seconds since epoch
>     pid: 1 # policy id, it must be the same as the policy id in the client token
>     policy: # policies for this client
>       type: !BlackList # !WhiteList or !BlackList
>       policies: # list of policies
>         - !Ip # policy based on the destination ip address
>           - !Any # !Any means any agent, !Agent agent_name means the agent with the name agent_name
>           - UDP # protocol
> ```
It seems that you forgot to mention IP address the port.
```yaml
secret: [118,101,72,65,78,82,69,78] # The secret for signing tokens, It must be the same as the gateway token secret, it is as byte array
tokens: # list of tokens
  - !Client # client token
    uid: 1a3248b2-d78e-415b-abbc-4aa781afae65 # client uid, please use a unique uid for each user
    name: client01 # client name, please use a unique name for each client
    exp: 1710227806 # expiration time in seconds since epoch
    policies: [1] # list of policy ids, it must be the same as the policy id in the client policy token, all the policies must be satisfied

  - !ClientPolicy # client policy token
    uid: 1a3248b2-d78e-415b-abbc-4aa781afae65
    name: client01 # client name, please use a unique name for each client
    exp: 1710227806 # expiration time in seconds since epoch
    pid: 1 # policy id, it must be the same as the policy id in the client token
    policy: # policies for this client
      type: !BlackList # !WhiteList or !BlackList
      policies: # list of policies
        - !Ip # policy based on the destination ip address
          - !Any # !Any means any agent, !Agent agent_name means the agent with the name agent_name
          - 0.0.0.0/0 # destination domain name
          - 443 # destination port
          - UDP # protocol
```


The policy token is optional, so you can create something like:
```yaml
secret: [118,101,72,65,78,82,69,78] # The secret for signing tokens, It must be the same as the gateway token secret, it is as byte array
tokens: # list of tokens
  - !Client # client token
    uid: 1a3248b2-d78e-415b-abbc-4aa781afae65 # client uid, please use a unique uid for each user
    name: client01 # client name, please use a unique name for each client
    exp: 1710227806 # expiration time in seconds since epoch
    # policies: [] # list of policy ids, it must be the same as the policy id in the client policy token, all the policies must be satisfied
```
