### DISCUSSION TITLE
Cannot connect to gateway when using ip address

### DISCUSSION THREAD

**Discussion by Dharisd** [narrowlink/narrowlink#76] [Q&A]
**Describe the bug**
When i try connect to the gateway using ```narrowlink list``` i get ```Unable to connect to the gateway: IO Error: received corrupt message of type InvalidContentType``` and ``` WARN narrowlink_gateway::service::ws: invalid HTTP method parsed``` on the gateway

**To Reproduce**
Im using ubuntu 22.04 as gateway server and have tried linux and mac os as client and agent this is my config file for the gateway, please note that i dont have a domain 
```yaml name: basic-tutorial # name of the gateway, it currently has no effect
secret: [1,2,3,4,5,6,7,8] # secret key for the gateway is used to authenticate clients and agents, at least 8 bytes
services: # list of services
- !Wss # secure (TLS) websocket service
  domains: ["my_ip:443"] # list of domains that this service should listen to
  listen_addr: "0.0.0.0:443" # address to listen to
  tls_config: !Acme # TLS configuration
    email: "email@domain.example" # email address to register with Let's Encrypt
    challenge_type: Http01 # Http01 or TlsAlpn01 (default: Http01)
    directory_url: https://acme-v02.api.letsencrypt.org/directory # Let's Encrypt directory URL
- !Ws # insecure websocket service
  domains: ["my_ip:80"] # list of domains that this service should listen to
  listen_addr: "0.0.0.0:80" # address to listen to
````

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by SajjadPourali** [comment]
@Dharisd It looks like you are trying to connect to the gateway using the HTTP protocol, while the client is attempting to connect using HTTPS. Setting port 80 is not sufficient for the client to use HTTP; you also need to set `protocol: Ws` (for version 0.2.x) or `service_type: Wss` (for version 0.1.x)  in your clients/agents configuration.

[0.1.x configuration](https://web.archive.org/web/20231007234559/https://narrowlink.com/docs/client#configuration)
[0.2.x configuration](https://narrowlink.com/docs/client#configuration)


https://github.com/narrowlink/narrowlink/discussions/59#discussioncomment-7087127

You also don't need to enable `!Wss` when you are not going to using a valid domain name.
```yaml
secret: [1,2,3,4,5,6,7,8] # secret key for the gateway is used to authenticate clients and agents, at least 8 bytes
services: # list of services
- !Ws # insecure websocket service
  domains: ["my_ip:80"] # list of domains that this service should listen to
  listen_addr: "0.0.0.0:80" # address to listen to
```
is sufficient.

**Comment by Dharisd** [comment]
after setting  ```protocol: Ws``` in client config and deleting !Wss  block from gateway config i get ```Unable to connect to the gateway: Unable To Upgrade: 200``` on the client

**Comment by SajjadPourali** [comment]
> after setting `protocol: Ws` in client config and deleting !Wss block from gateway config i get `Unable to connect to the gateway: Unable To Upgrade: 200` on the client

It means the gateway you've set is not equal to one of the addresses in the `domains`. If the IP address is 127.17.21.12, the configuration should be something similar to the following example (without port number in the `domains`):

```yaml
secret: [1,2,3,4,5,6,7,8] # secret key for the gateway is used to authenticate clients and agents, at least 8 bytes
services: # list of services
- !Ws # insecure websocket service
  domains: ["127.17.21.12"] # list of domains that this service should listen to
  listen_addr: "0.0.0.0:80" # address to listen to
```
